name: Deploy via Git Pull
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ALIYUN_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          script: "cd /opt/1panel/apps/openresty/openresty/www/sites/dptech/index && git pull --rebase && chmod -R 755 ."
