name: Deploy via Git Pull
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trigger Server Update
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_ed25519 \
              deployer@${{ secrets.ALIYUN_SERVER_IP }} \
              "cd /opt/1panel/apps/openresty/openresty/www/sites/dptech/index && git pull --rebase && chmod -R 755 ."
        env:
          ALIYUN_SERVER_IP: ${{ secrets.ALIYUN_SERVER_IP }}